spring.application.name=backend

# =========================
# Database Configuration
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# File Upload
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Swagger
# =========================
springdoc.swagger-ui.path=/swagger-ui.html

# =========================
# Server Port
# =========================
server.port=${PORT:25220}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
#  rozorpay payment gateway
razorpay.key=rzp_live_TAHPsInsNF3Z68
razorpay.secret=7EULMRU0bHavgA6hgzbKYToT