spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/PadhaikaAddaa
spring.datasource.username=root
spring.datasource.password=Alok@11215111
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081

jwt.secret=ThisIsMySuperSecretKeyForJWTAuthentication123456789
jwt.expiration=86400000
